name: deployment to aks
on: [push]
permissions:
  id-token: write
  contents: read

jobs:
  docker_build_push_acr:
    runs-on: ubuntu-latest
    name: create and push docker image to acr
    environment: deployment    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: azure login 
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id:  ${{ secrets.TENANT_ID }}
        subscription-id:  ${{ secrets.SUBSCRIPTION_ID }}
        
    - name: docker install
      uses: docker/setup-docker-action@v4.1.0

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reactuitodoapp
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reactuitodoapp
        
        
  deploy_to_aks:
    runs-on: ubuntu-latest
    name: deploy to aks using helm
    needs: [docker_build_push_acr]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: helm_dep
          cluster-name: helm_deployyy
          admin: 'false'
          use-kubelogin: 'true'

      # Deploys application based on manifest files from previous step
      - name: Deploy application
        run: helm install ./todoapp_helm/ -f ./todoapp_helm/dev.values.yaml
    
  
  
