name: deployment to aks
on: [workflow_dispatch]
permissions:
  id-token: read  

jobs:
  docker_build_push_acr:
    runs-on: ubuntu-latest
    name: create and push docker image to acr
    environment: deployment    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: azure login 
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id:  ${{ secrets.TENANT_ID }}
        subscription-id:  ${{ secrets.SUBSCRIPTION_ID }}
        
    - name: docker install
      uses: docker/setup-docker-action@v4.1.0

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reactuitodoapp
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reactuitodoapp
        
        
  
  
  
